[book]
authors = ["Erg dev team"]
# language = "en"
multilingual = true
src = "dev_guide"
title = "Guide to erg Development"

# [build]
# build-dir = "docs"

[output.html]
additional-css = [
    "theme/css/error.css",
]
additional-js = [
    "theme/js/lz-string.min.js",
]
git-repository-url = "https://github.com/erg-lang/erg/tree/main/doc/"
